baseURL = "http://hichenxinyu.github.io"
title = "Nevea"
theme = "hugo-theme-even"

languageCode = "cn"
hasCJKLanguage = true
pygmentsCodeFences = true
disableFastRender = true
pygmentsUseClasses = true

# You can use favicon by addin them manually.
useIcon = true

# ignore build error in local machine
ignoreErrors = ["error-remote-getjson"]