name: CI #自动化的名称
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - hugo
jobs:
  build:
    runs-on: ubuntu-latest # 镜像市场
    steps:
      - name: checkout # 步骤的名称
        uses: actions/checkout@master #软件市场的名称
        with: # 参数
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: '0.68.1'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY}}
          EXTERNAL_REPOSITORY: hichenxinyu/hichenxinyu.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
   
      - name: Mirror github coding
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY}}
        with:
          source-repo: 'git@github.com:hichenxinyu/hichenxinyu.github.io.git'
          destination-repo: 'git@e.coding.net:nevea/blog_nevea.git'